basic_app/urls.py
from django.urls import path
from . import views

app_name = 'basic_app'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login', views.user_login, name='login')
]

learning_users/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('', views.index, name='index'),
    path('basic_app/', include('basic_app.urls')),
    path('logout/', views.user_logout, name='logout'),
    path('special/', views.special, name='special'),
    path('admin/', admin.site.urls),
]

basic_app/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    portfolio_site = models.URLField(blank=True)
    profile_picture = models.ImageField(upload_to='profile_pictures', blank=True)

    def __str__(self):
        return self.user.username

basic_app/forms.py
from django import forms
from .models import UserProfileInfo
from django.contrib.auth.models import User

form_control_class = 'form-control'


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': form_control_class}))
    username = forms.CharField(widget=forms.TextInput(attrs={'class': form_control_class}))
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': form_control_class}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': form_control_class}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': form_control_class}))

    class Meta:
        model = User
        fields = ['username', 'password', 'email', 'first_name', 'last_name']


class UserProfileInfoForm(forms.ModelForm):
    portfolio_site = forms.CharField(widget=forms.URLInput(attrs={'class': form_control_class}))

    class Meta:
        model = UserProfileInfo
        fields = ['portfolio_site', 'profile_picture']

basic_app/views.py
from django.shortcuts import render
from .forms import UserForm, UserProfileInfoForm

from django.urls import reverse
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout


# Create your views here.
def index(req):
    data = {'title': 'Home'}
    return render(req, 'basic_app/index.html', context=data)


def register(req):
    registered = False

    if req.method == 'POST':
        # check form validity
        user_form = UserForm(req.POST)
        user_profile_form = UserProfileInfoForm(req.POST)

        if user_form.is_valid() and user_profile_form.is_valid():
            user = user_form.save(commit=False)
            user.set_password(user.password)
            user.save()

            user_profile = user_profile_form.save(commit=False)
            user_profile.user = user

            # Profile picture
            if 'profile_picture' in req.FILES:
                user_profile.profile_picture = req.FILES['profile_picture']

            user_profile.save()
            registered = True

        else:
            print('FORM INVALID')
            print(user_form.errors, user_profile_form.errors)
    else:
        user_form = UserForm()
        user_profile_form = UserProfileInfoForm()

    data = {'title': 'Register', 'user_form': user_form,
            'user_profile_form': user_profile_form, 'registered': registered}
    return render(req, 'basic_app/registration.html', context=data)


def user_login(req):
    if req.method == 'POST':
        username = req.POST.get('username')
        password = req.POST.get('password')

        user = authenticate(username=username, password=password)

        if user is not None:
            if user.is_active:
                login(req, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                # User is not active anymore
                return HttpResponse('ACCOUNT NOT ACTIVE')
        else:
            # bad credentials
            print('Failed login attempt')
            print('Username %s, Password %s' % (username, password))
            return HttpResponse('BAD CREDENTIALS')

    else:
        return render(req, 'basic_app/login.html')


@login_required
def user_logout(req):
    logout(req)
    return HttpResponseRedirect(reverse('index'))


@login_required
def special(req):
    return HttpResponse('Something special')

templates/basic_app/index.html
{% extends 'basic_app/master.html' %}

{% block content %}
    <div class="row">
        <div class="col-12">
            <h1>Welcome to Django</h1>
        </div>
    </div>
{% endblock %}

templates/basic_app/login.html
{% extends 'basic_app/master.html' %}

{% block content %}
    <div class="row">
        <div class="col-12">

            <h1>Please login</h1>

            <div class="mt-5 row justify-content-center">

                <div class="col-4 px-3 py-2">

                    <form action="{% url 'basic_app:login' %}" method="POST">

                        {% csrf_token %}

                        <div class="row">
                            <div class="col-12">
                                <div class="form-group">
                                    <label for="username">Username</label>
                                    <input type="text" class="form-control" id="username" name="username">
                                </div>
                            </div>

                            <div class="col-12">
                                <div class="form-group">
                                    <label for="password">Password</label>
                                    <input type="password" class="form-control" id="password" name="password">
                                </div>
                            </div>

                            <div class="col-12">
                                <button class="btn-primary btn btn-block">Login</button>
                            </div>
                        </div>

                    </form>

                </div>

            </div>

        </div>

    </div>

{% endblock %}

templates/basic_app/master.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
          crossorigin="anonymous">
    <title>Django - {{ title }}</title>
</head>
<body>

    <!-- NAVBAR START -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#">Django - {{ title }}</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'index' %}">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'basic_app:register' %}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'basic_app:login' %}">Login</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <!-- END NAVBAR START -->

    <div class="container">
        {% block content %}
            {# CONTENT GOES HERE #}
        {% endblock %}
    </div>

</body>
</html>

templates/basic_app/registration.html
{% extends 'basic_app/master.html' %}
{% load staticfiles %}

{% block content %}
    <div class="row">
        <div class="col-12">

            {% if registered %}
                <h1>Thank you for registering!</h1>
            {% else %}
                <h1>Register</h1>
                <h3>Fill out the form</h3>

                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}

                    <div class="row">
                        <div class="col-12 col-md-4">
                            <div class="form-group">
                                {{ user_form.first_name.label_tag }}
                                {{ user_form.first_name }}
                                {{ user_form.first_name.errors }}
                            </div>
                            <div class="form-group">
                                {{ user_form.last_name.label_tag }}
                                {{ user_form.last_name }}
                                {{ user_form.last_name.errors }}
                            </div>
                            <div class="form-group">
                                {{ user_form.email.label_tag }}
                                {{ user_form.email }}
                                {{ user_form.email.errors }}
                            </div>
                            <div class="form-group">
                                {{ user_form.username.label_tag }}
                                {{ user_form.username }}
                                {% if user_form.username.errors %}
                                    {{ user_form.username.errors }}
                                {% endif %}
                            </div>
                            <div class="form-group">
                                {{ user_form.password.label_tag }}
                                {{ user_form.password }}
                                {{ user_form.password.errors }}
                            </div>
                        </div>
                        <div class="col-12 col-md-4">
                            <div class="form-group">
                                {{ user_profile_form.portfolio_site.errors }}
                                {{ user_profile_form.portfolio_site.label_tag }}
                                {{ user_profile_form.portfolio_site }}
                            </div>
                            <div class="form-group">
                                {{ user_profile_form.profile_picture.errors }}
                                {{ user_profile_form.profile_picture.label_tag }}
                                {{ user_profile_form.profile_picture }}
                            </div>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-auto">
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </div>
                </form>
            {% endif %}

        </div>
    </div>
{% endblock %}